language: csharp
solution: RunInfoBuilder.sln
install:
  - nuget restore RunInfoBuilder.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RunInfoBuilder.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Test/FunctionalTests/bin/Release/netcoreapp2.1/R5.RunInfoBuilder.FunctionalTests.dll